name: "TSF evidence linker"
description: "Link tsffer-generated evidence items to TSF project statements, score tsf tree and generate report"

inputs:
  tsffer_url:
    description: "(Optional) URL pointing to tsffer metadata artifact archive. If not provided, will retrieve tsffer artifacts from GH CI artifact store."
    required: false

outputs:
  trudag_score:
    description: "TSF score computed after linking evidence refs"
  trudag_report:
    description: "Name of archive file containing trudag-generated report"

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.tsffer_url }}
