name: "TSF evidence linker"
description: "Link CI-generated evidence items to TSF project statements"

inputs:
  github_token:
    description: 'GitHub token.'
    required: false
    default: ${{ github.token }}
  echo:
    description: "String to ping"
    required: true

outputs:
  result:
    description: "Tool result"

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.echo }}
