name: "TSF evidence linker"
description: "Link CI-generated evidence items to TSF project statements"

inputs:
  github_token:
    description: 'GitHub token.'
    required: false
    default: ${{ github.token }}
  echo:
    description: "String to ping"
    required: true
  tsffer_url:
    description: "(Optional) URL pointing to tsffer metadata artifact archive. If not provided, will retrieve tsffer artifacts from GH CI artifact store."
    required: false

outputs:
  version:
    description: "Tool version"
  files:
    description: "Number of files"
  result:
    description: "Tool result"

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.tsffer_url }}
